Global:
  # 是否使用cuda
  use_cuda: True
  # 模型保存的位置
  save_dir: './model_weight_9_23'
  # 训练集数据地址
  train_dataset_path: 'datasets_book_spine/train'
  # 验证集数据地址
  val_dataset_path: 'datasets_book_spine/val'
  # 图像编码器的输入尺寸
  input_shape: [224, 224]
  # 文本编码器的文本长度
  context_length: 120
  # batch大小
  batch_size: 32
  # 优化器的类型 ['adam' , 'sgd']
  optimizer_type: 'adam'
  # 学习率调整策略 ['StepLR','ReduceLROnPlateau']
  lr_schedular_type: 'StepLR'
  # 是否使用多线程读取数据，0代表关闭多线程
  num_workers: 16
  # 是否使用DDP模式训练数据
  distributed: False
  # 是否使用预训练权重
  pretrained: True
  num_epoch: 300
